-- The new catalogue: 62 products (27 the system already had, 35 new).
-- Generated by scripts/inventory/build-migration.mjs from scripts/inventory/new-inventory.csv
-- (the warehouse's list, checked against the live system with the sales team on 2026-09-23).
-- Do not edit by hand.
--
-- * A product the system already had keeps its row, SKU, price, stock and movement history and
--   only takes the warehouse's name and category. Keeping the row is what keeps its order lines,
--   the VIP price code, the free-sample codes and the plasma packages pointing at it.
-- * A new product is inserted with the price the sales team gave and an opening stock of 0: no
--   count was taken for these, and a guessed figure would be worse than an honest zero.
-- * Everything else is retired with is_active = false, as 020 did. inventory_movements is
--   ON DELETE RESTRICT, and the catalogue, order entry and business_resolve_product all filter
--   on is_active, so a retired product stops being offered but its history stays readable.
--   A package stays active only while every one of its bottles is still in the catalogue.
BEGIN;

INSERT INTO public.categories (slug, name_ar, name_en) VALUES
  ('plasma-hair-care', 'بلازما العناية بالشعر', 'Plasma Hair Care'),
  ('professional-proteins', 'بروتينات الشعر الاحترافية', 'Professional Hair Proteins'),
  ('morphosis-professional', 'مورفوزيس بروفيشنال الإيطالي', 'Morphosis Professional'),
  ('argan-hair-care', 'العناية بالشعر بالأرجان', 'Argan Hair Care'),
  ('hair-care', 'العناية بالشعر', 'Hair Care'),
  ('electrical-styling', 'أجهزة التصفيف الكهربائية', 'Electrical Styling Tools'),
  ('beto-lenses', 'عدسات بيتو ومستلزماتها', 'Beto Contact Lenses')
ON CONFLICT (slug) DO UPDATE SET is_active = true;

CREATE TEMP TABLE new_catalogue (sku text PRIMARY KEY, name_ar text, name_en text, category text,
  retail_price numeric(10,3), cost_price numeric(10,3), stock int, reorder int) ON COMMIT DROP;
INSERT INTO new_catalogue VALUES
  ('PROT-MARACUJA-BLACK-1L-V2-07', 'ماراكوجا اسود لتر', 'Maracuja Black 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-MARACUJA-BLACK-100-V2-08', 'ماراكوجا اسود 100 مل', 'Maracuja Black 100ml', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-MARACUJA-HONEY-1L-V2-05', 'ماراكوجا بلص لتر', 'Maracuja Plus 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-MARACUJA-HONEY-100-V2-06', 'ماراكوجا بلص 100 مل', 'Maracuja Plus 100ml', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-THERAPY-100-V2-14', 'ثيرابي 100 مل', 'Therapy 100ml', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-DEVAY-PINK-1L-V2-09', 'ديفاي بلكس لتر', 'Divay Plex 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-DEVAY-BLUE-1L-V2-11', 'ديفاي بلو لتر', 'Divay Blue 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-DEVAY-PINK-100-V2-10', 'ديفاي بلكس 100 مل', 'Divay Plex 100ml', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-SP-GOLD-1L-V2-03', 'ذهبي SP لتر', 'Gold SP 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-SP-SILVER-1L-V2-01', 'فضي SP لتر', 'Silver SP 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PROT-DEVAY-BLUE-100-V2-12', 'ديفاي بلو 100 مل', 'Divay Blue 100ml', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('PL-SHMP-500-V2-01', 'شامبو بلازما 500 مل', 'Shampoo Plasma 500ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('PL-COND-500-V2-02', 'بلسم بلازما 500 مل', 'Conditioner Plasma 500ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('PL-SERUM-100-V2-04', 'سيرم بلازما 100 مل', 'Serum Plasma 100ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('PL-TREAT-500-V2-03', 'ماسك بلازما 500 مل', 'Mask Plasma 500ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('PL-TREAT-100-GIFT-V2-05', 'ماسك بلازما 100 مل', 'Mask Plasma 100ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('BT-ARG-01', 'شامبو ارجان ريبير 500 مل', 'Shampoo Argan Repair 500ml', 'argan-hair-care', 18.000, NULL, 0, 5),
  ('BT-ARG-02', 'بلسم ارجان ريبير 500 مل', 'Conditioner Argan Repair 500ml', 'argan-hair-care', 18.000, NULL, 0, 5),
  ('BT-ARG-03', 'شامبو ارجان هايدرو 500 مل', 'Shampoo Argan Hydro 500ml', 'argan-hair-care', 18.000, NULL, 0, 5),
  ('BT-ARG-04', 'بلسم ارجان هايدرو 500 مل', 'Conditioner Argan Hydro 500ml', 'argan-hair-care', 18.000, NULL, 0, 5),
  ('MOR-RESTRUCT-SET-250-V2-03', 'مور شامبو + بلسم 250 مل', 'Morphosis Shampoo + Conditioner 250ml', 'morphosis-professional', NULL, NULL, NULL, NULL),
  ('BT-MOR-01', 'شامبو مور ريبير لتر', 'Shampoo Morphosis Repair 1L', 'morphosis-professional', 28.000, NULL, 0, 5),
  ('BT-MOR-02', 'بلسم مور ريبير لتر', 'Conditioner Morphosis Repair 1L', 'morphosis-professional', 28.000, NULL, 0, 5),
  ('BT-MOR-03', 'شامبو مور صابليمز لتر', 'Shampoo Morphosis Sublime 1L', 'morphosis-professional', 28.000, NULL, 0, 5),
  ('BT-MOR-04', 'بلسم مور صابليمز لتر', 'Conditioner Morphosis Sublime 1L', 'morphosis-professional', 28.000, NULL, 0, 5),
  ('BT-MOR-05', 'شامبو ريستركشر لتر', 'Shampoo Restructure 1L', 'morphosis-professional', 28.000, NULL, 0, 5),
  ('MOR-FILLER-1L-V2-07', 'فيلر لتر', 'Filler 1L', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('MOR-FILLER-150-V2-08', 'فيلر 100 مل', 'Filler 100ml', 'professional-proteins', NULL, NULL, NULL, NULL),
  ('MOR-LEAVEIN-150-V2-05', 'ليف ان 125 مل', 'Leave In 125ml', 'morphosis-professional', NULL, NULL, NULL, NULL),
  ('MOR-SERUM-150-V2-06', 'سيرم مور 125 مل', 'Serum Morphosis 125ml', 'morphosis-professional', NULL, NULL, NULL, NULL),
  ('MOR-FALLKIT-NAHDI-V2-09', 'كت تساقط نهدي', 'Kit Hair Loss Nahdi', 'hair-care', NULL, NULL, NULL, NULL),
  ('MOR-FALLKIT-BLUE-V2-10', 'كت تساقط ازرق', 'Kit Hair Loss Blue', 'hair-care', NULL, NULL, NULL, NULL),
  ('BT-TOOL-01', 'مكبس اسود', 'Hair Straightener Black', 'electrical-styling', 35.000, NULL, 0, 5),
  ('BT-TOOL-02', 'مكبس ذهبي', 'Hair Straightener Gold', 'electrical-styling', 35.000, NULL, 0, 5),
  ('BT-LENS-01', 'Gray Natural (120)', 'Gray Natural (120)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-02', 'Gray Talent (222)', 'Gray Talent (222)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-03', 'Gray Venus (111)', 'Gray Venus (111)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-04', 'Sheraz Gray Green (200)', 'Sheraz Gray Green (200)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-05', 'Sheraz Gray Honey (204)', 'Sheraz Gray Honey (204)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-06', 'Sheraz Yallow (201)', 'Sheraz Yallow (201)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-07', 'Sheraz Gray Blue (203)', 'Sheraz Gray Blue (203)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-08', 'Meral Gray (99)', 'Meral Gray (99)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-09', 'Meral Light Gray (100)', 'Meral Light Gray (100)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-10', 'Meral Blue (103)', 'Meral Blue (103)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-11', 'Meral Green (102)', 'Meral Green (102)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-12', 'Meral Honey (104)', 'Meral Honey (104)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-13', 'Meral Talent (333)', 'Meral Talent (333)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-14', 'Meral Yallow (101)', 'Meral Yallow (101)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-15', 'Nutella (123)', 'Nutella (123)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-16', 'Black Coffee (55)', 'Black Coffee (55)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-17', 'Green Natural (121)', 'Green Natural (121)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-18', 'Honey Natural (122)', 'Honey Natural (122)', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-19', 'Meral Green (102) power', 'Meral Green (102) power', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-LENS-20', 'Meral Gray (99) power', 'Meral Gray (99) power', 'beto-lenses', 25.000, NULL, 0, 5),
  ('BT-TOOL-03', 'سشوار ماك', 'Hair Dryer Mac', 'electrical-styling', 40.000, NULL, 0, 5),
  ('EL-TURBO-V2-02', 'سشوار تيربو ستار', 'Hair Dryer Turbo Star', 'electrical-styling', NULL, NULL, NULL, NULL),
  ('BT-PLS-01', 'شامبو بلازما 5 لتر', 'Shampoo Plasma 5L', 'plasma-hair-care', 25.000, NULL, 0, 5),
  ('BT-PLS-02', 'بلسم بلازما 5 لتر', 'Conditioner Plasma 5L', 'plasma-hair-care', 25.000, NULL, 0, 5),
  ('BT-LENS-21', 'محلول عدسات', 'Solution Lenses', 'beto-lenses', 5.000, NULL, 0, 5),
  ('PL-SAMP-SHMP-15-01', 'شامبو بلازما سشيت 15 مل', 'Shampoo Plasma Sachet 15ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('PL-SAMP-COND-15-02', 'بلسم بلازما سشيت 15 مل', 'Conditioner Plasma Sachet 15ml', 'plasma-hair-care', NULL, NULL, NULL, NULL),
  ('PL-SAMP-TREAT-15-03', 'ماسك بلازما سشيت 15 مل', 'Mask Plasma Sachet 15ml', 'plasma-hair-care', NULL, NULL, NULL, NULL);

DO $$
DECLARE missing text;
BEGIN
  SELECT string_agg(n.sku, ', ') INTO missing FROM new_catalogue n
  WHERE n.retail_price IS NULL AND NOT EXISTS (SELECT 1 FROM public.products p WHERE p.sku = n.sku);
  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'new catalogue: % should already exist but the system has no such sku', missing;
  END IF;
END $$;

-- The ones the system already had: new name and category, everything else as it was.
UPDATE public.products p SET name_ar = n.name_ar, name_en = n.name_en, category_id = c.id,
  retail_price = coalesce(n.retail_price, p.retail_price), cost_price = coalesce(n.cost_price, p.cost_price),
  is_active = true, updated_at = now()
FROM new_catalogue n JOIN public.categories c ON c.slug = n.category
WHERE p.sku = n.sku;

UPDATE public.inventory i SET quantity_on_hand = coalesce(n.stock, i.quantity_on_hand),
  reorder_level = coalesce(n.reorder, i.reorder_level), updated_at = now()
FROM new_catalogue n JOIN public.products p ON p.sku = n.sku
WHERE i.product_id = p.id AND (n.stock IS NOT NULL OR n.reorder IS NOT NULL);

-- The new ones.
INSERT INTO public.products (sku, name_ar, name_en, category_id, retail_price, cost_price, is_active)
SELECT n.sku, n.name_ar, n.name_en, c.id, n.retail_price, coalesce(n.cost_price, 0), true
FROM new_catalogue n JOIN public.categories c ON c.slug = n.category
WHERE NOT EXISTS (SELECT 1 FROM public.products p WHERE p.sku = n.sku);

-- Every catalogue product that is not a package gets a stock row (the free samples had none).
INSERT INTO public.inventory (product_id, quantity_on_hand, quantity_reserved, reorder_level)
SELECT p.id, coalesce(n.stock, 0), 0, coalesce(n.reorder, 5)
FROM new_catalogue n JOIN public.products p ON p.sku = n.sku
WHERE NOT EXISTS (SELECT 1 FROM public.product_bundles b WHERE b.bundle_product_id = p.id)
ON CONFLICT (product_id) DO NOTHING;

-- Retire the rest. A package survives only if all its bottles did.
UPDATE public.products p SET is_active = false, updated_at = now()
WHERE p.is_active AND p.sku NOT IN (SELECT sku FROM new_catalogue)
  AND NOT (EXISTS (SELECT 1 FROM public.product_bundles b WHERE b.bundle_product_id = p.id)
    AND NOT EXISTS (SELECT 1 FROM public.product_bundles b JOIN public.products c ON c.id = b.component_product_id
      WHERE b.bundle_product_id = p.id AND c.sku NOT IN (SELECT sku FROM new_catalogue)));

DO $$ BEGIN
  IF (SELECT count(*) FROM public.products p JOIN new_catalogue n ON n.sku = p.sku WHERE p.is_active) <> 62 THEN
    RAISE EXCEPTION 'new catalogue: expected 62 active products from the list';
  END IF;
END $$;

COMMIT;
